services:
  sandstorm:
    image: chourmovs/issdedicated:main
    container_name: sandstorm
    restart: unless-stopped

    # Réseaux/ports
    ports:
      - "27102:27102/udp"   # Game
      - "27131:27131/udp"   # Query
      - "15000:15000/udp"   # Beacon
      - "27015:27015/tcp"   # RCON (laisser vide côté env pour l'XP)

    # Stockage
    volumes:
      - /opt/sandstorm:/opt/sandstorm    # binaires + configs + workshop
      - /opt/steam:/home/steam/Steam     # cache SteamCMD

    # UID/GID host
    user: "1000:1000"

    environment:
      # ────────── Base serveur ──────────
      GAMEDIR: "/opt/sandstorm"
      AUTO_UPDATE: "1"
      TZ: "Europe/Paris"

      SS_HOSTNAME: "CHOURMOVS ISS • Ranked COOP + PUSH"
      SS_MAXPLAYERS: "24"

      # Par défaut (le MapCycle alternera les modes)
      SS_GAME_MODE: "Checkpoint"
      SS_SCENARIO: "Scenario_Farmhouse_Checkpoint_Security"

      # Autoriser le versus + valider le MapCycle
      SS_FORCE_COOP_ONLY: "0"
      SS_VALIDATE_MAPCYCLE: "1"

      # ────────── MapCycle mix COOP + PUSH ──────────
      SS_MAPCYCLE: |
        # --- COOP (Checkpoint) ---
        Scenario_Farmhouse_Checkpoint_Security
        Scenario_Crossing_Checkpoint_Security
        Scenario_Hideout_Checkpoint_Security

        # --- VERSUS (Push) ---
        Scenario_Farmhouse_Push_Security

        # --- COOP ---
        Scenario_Refinery_Checkpoint_Security
        Scenario_Summit_Checkpoint_Security
        Scenario_Hillside_Checkpoint_Security

        # --- VERSUS (Push) ---
        Scenario_Ministry_Push_Security

        # --- COOP ---
        Scenario_Precinct_Checkpoint_Security
        Scenario_Ministry_Checkpoint_Security
        Scenario_Outskirts_Checkpoint_Security
        Scenario_PowerPlant_Checkpoint_Security

        # --- VERSUS (Push) ---
        Scenario_Crossing_Push_Security
        Scenario_Precinct_Push_Security

      # ────────── QoL / Vote / Timers ──────────
      SS_KILL_FEED: "1"
      SS_KILL_CAMERA: "0"
      SS_VOICE_ENABLED: "1"
      SS_FRIENDLY_FIRE_SCALE: "0.2"
      SS_ROUND_TIME: "900"
      SS_POST_ROUND_TIME: "15"
      SS_VOTE_ENABLED: "1"
      SS_VOTE_PERCENT: "0.6"

      # ────────── Bots (COOP & VERSUS) ──────────
      # Ces valeurs garantissent des bots en Push/FF/Dom (écrites dans INSMultiplayerMode + section de mode)
      SS_BOTS_ENABLED: "1"
      SS_BOT_NUM: "6"          # base
      SS_BOT_QUOTA: "4"        # fill côté versus
      SS_BOT_DIFFICULTY: "0.85"

      # Affinage COOP (optionnel)
      SS_FRIENDLY_BOT_QUOTA: "0"
      SS_MIN_ENEMIES: "6"
      SS_MAX_ENEMIES: "16"

      # ────────── XP / Stats ──────────
      SS_ENABLE_STATS: "1"
      GSLT_TOKEN: ""
      GAMESTATS_TOKEN : ""
      
      RCON_PASSWORD: ""                # DOIT rester vide pour l'XP classé
      SS_ALLOW_MODS_WHEN_RANKED: "1"   # protège l'XP si des mods sont définis par erreur

      # ────────── Mods/Mutators (désactivés pour XP) ──────────
      # Laisse tout vide pour rester "ranked".
      SS_MODS: ""
      SS_MUTATORS_VERSUS: ""
      SS_MUTATORS_PUSH: ""
      SS_MUTATORS_FIREFIGHT: ""
      SS_MUTATORS_DOMINATION: ""
      SS_MUTATORS_SKIRMISH: ""

      # ────────── Admins ──────────
      # Remplace par tes SteamID64 si besoin (séparés par virgules)
      SS_ADMINS: ""

      # 1) Skill de base
      AIMOD_DIFFICULTY: "0.6"
      AIMOD_ACCURACY: "0.6"
      AIMOD_REACTION: "0.6"

      # 2) Sight / vision
      AIMOD_SIGHT_ALERT: ""
      AIMOD_SIGHT_IDLE: ""
      AIMOD_SIGHT_SMOKE: ""
      AIMOD_SIGHT_SMOKE_EYE: ""
      AIMOD_SIGHT_SMOKE_EYE_FRAC: ""
      AIMOD_MIN_LI_SEE: ""
      AIMOD_MIN_LI_NIGHT: ""
      AIMOD_LI_FULLY_VISIBLE: ""
      AIMOD_TIME_NOTICE_VISIB_MULT: ""
      AIMOD_MIN_LI_AFFECT_NV: ""
      AIMOD_MIN_NV_STRENGTH: ""

      # 3) Chances d’être spotté
      AIMOD_CH_SPRINT_MULT: ""
      AIMOD_CH_MOVING_MULT: ""
      AIMOD_CH_STAND_DIST: ""
      AIMOD_CH_STAND_CLOSE: ""
      AIMOD_CH_CROUCH_DIST: ""
      AIMOD_CH_CROUCH_CLOSE: ""
      AIMOD_CH_PRONE_DIST: ""
      AIMOD_CH_PRONE_CLOSE: ""

      # 4) Ouïe
      AIMOD_HEAR_AWARE_RADIAL: ""
      AIMOD_HEAR_AWARE_GUNSHOT: ""
      AIMOD_HEAR_AWARE_SPRINT: ""
      AIMOD_HEAR_AWARE_FOOT: ""
      AIMOD_HEAR_DIST_SPRINT: ""
      AIMOD_HEAR_DIST_RUN: ""
      AIMOD_HEAR_Z_MIN: ""
      AIMOD_HEAR_Z_MAX: ""
      AIMOD_HEAR_FENCED_MOD: ""

      # 5) Vitesse de rotation
      AIMOD_TURNSPD_MAX_ANGLE_TH: ""
      AIMOD_TURNSPD_MIN_ANGLE_TH: ""
      AIMOD_TURNSPD_MAX: ""
      AIMOD_TURNSPD_MIN: ""
      AIMOD_TURNSPD_DIST_TH: ""
      AIMOD_TURNSPD_SCALE_MAX: ""
      AIMOD_TURNSPD_SCALE_MIN: ""

      # 6) Attaque & distances
      AIMOD_ATTACK_DELAY_CLOSE: ""
      AIMOD_ATTACK_DELAY_DIST: ""
      AIMOD_ATTACK_DELAY_MELEE: ""
      AIMOD_DISTANCE_RANGE: ""
      AIMOD_CLOSE_RANGE: ""
      AIMOD_MID_RANGE: ""
      AIMOD_FAR_RANGE: ""
      AIMOD_MELEE_RANGE: ""

      # 7) Précision / bloatbox
      AIMOD_ACCURACY_MULT: ""
      AIMOD_SUPPRESS_ACCURACY_MULT: ""
      AIMOD_NIGHT_ACC_FACTOR: ""
      AIMOD_ZERO_TIME_EASY: ""
      AIMOD_ZERO_TIME_MED: ""
      AIMOD_ZERO_TIME_HARD: ""
      AIMOD_BLOAT_MULT_EASY: ""
      AIMOD_BLOAT_MULT_MED: ""
      AIMOD_BLOAT_MULT_HARD: ""
      AIMOD_BLOAT_DIST_MULT: ""
      AIMOD_BLOAT_MAX_DIST: ""
      AIMOD_BLOAT_MIN_DIST: ""

      # 8) Comportements offensifs / cover / wander / flanking
      AIMOD_CHANCE_COVER: ""
      AIMOD_CHANCE_COVER_IMPRO: ""
      AIMOD_CHANCE_COVER_FAR: ""
      AIMOD_MAX_DIST_2COVER: ""
      AIMOD_CHANCE_WANDER: ""
      AIMOD_DEF_WANDER_DIST: ""
      AIMOD_WANDER_DIST_MAX_MULT: ""
      AIMOD_CHANCE_FLANK: ""
      AIMOD_CHANCE_RUSH: ""
      AIMOD_CHANCE_HUNT: ""
      AIMOD_CHANCE_FORCE_HUNT: ""
      AIMOD_CHANCE_REGROUP: ""

      # 9) Spotting / leaning / injured / hearing min
      AIMOD_BONUS_SPOT_START: ""
      AIMOD_MAX_BONUS_SPOT_HEAR: ""
      AIMOD_MAX_BONUS_SPOT_ALERT: ""
      AIMOD_CH_LEAN_MULT: ""
      AIMOD_MIN_CHANCE_HEAR: ""
      AIMOD_INJ_DMG_TH: ""
      AIMOD_INJ_HP_RATIO: ""

      # 10) Objectifs
      AIMOD_DIST_NEAR_OBJ: ""
      AIMOD_DIST_MID_OBJ: ""
      AIMOD_DIST_FAR_OBJ: ""
      AIMOD_RATIO_BOTS_CLOSE_OBJ: ""

      # 11) Suppression / NLOS / durées / distances
      AIMOD_STOP_FIRE_NLOS_MIN: ""
      AIMOD_STOP_FIRE_NLOS_MAX: ""
      AIMOD_SUPPR_TIME_MIN: ""
      AIMOD_SUPPR_TIME_MAX: ""
      AIMOD_SUPPR_MIN_DIST: ""
      AIMOD_SUPPR_BASE_CH: ""
      AIMOD_SUPPR_ADD_FRIEND: ""

      # 12) Head/body ratio (doublon volontaire)
      AIMOD_HEAD2BODY_RATIO: ""
      AIMOD_RATIO_AIM_HEAD: ""

      # 13) Difficulté variable selon # joueurs
      AIMOD_VAR_PC_MIN: ""
      AIMOD_VAR_PC_MAX: ""
      AIMOD_VAR_MIN_DIFFICULTY: ""
      AIMOD_VAR_MAX_DIFFICULTY: ""

      # 14) Respawns & population
      AIMOD_MAXCOUNT: ""
      AIMOD_RESPAWN_MIN: ""
      AIMOD_RESPAWN_MAX: ""
      AIMOD_SPAWN_DELAY: ""

      # 15) Divers / toggles
      AIMOD_OVERWRITE_BOTCFG: ""
      AIMOD_BOT_USES_SMOKE: ""
      AIMOD_SUPPR_4MG_ONLY: ""
      AIMOD_MEMORY_MAX_AGE: ""

      # 16) Knife & squads
      AIMOD_ALLOW_MELEE: "0"
      AIMOD_STAY_IN_SQUADS: "1"
      AIMOD_SQUAD_SIZE: "2"
