services:
  sandstorm:
    build: .
    container_name: sandstorm
    environment:
      STEAM_USER: "anonymous"   # ou "anonymous"
      STEAM_PASS: ""  # vide si anonymous
      AUTO_UPDATE: "1"
      PORT: "27102"
      QUERYPORT: "27132"
      RCON_PASSWORD: "MonSuperMotDePasse!"
      EXTRA_ARGS: '-MaxPlayers=16'
    ports:
      - "27102:27102/udp"
      - "27103:27103/udp"
      - "27132:27132/udp"
      - "15000:15000/udp"
      - "27015:27015/tcp"
    volumes:
      - steam_auth:/home/steam/Steam
      - sandstorm_saved:/opt/sandstorm/Insurgency/Saved
      - sandstorm_cfg:/opt/sandstorm/Insurgency/Saved/Config/LinuxServer
    restart: unless-stopped

volumes:
  steam_auth:
  sandstorm_saved:
  sandstorm_cfg:
